# config/_default/hugo.yaml

# The URL of your site. This MUST be correct.
baseURL: 'https://idjoshi.github.io/'

# The name of your site.
title: 'Varun Joshi'

# The theme to use.
theme:
  - github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

#############################
# This sets your CV page as the homepage.
cascade:
  - _target:
      kind: page
      path: /authors/admin/**
    params:
      layout: cv
      is_homepage: true
#############################

# Do not change the settings below.
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
enableRobotsTXT: true
