baseURL: 'https://idjoshi.github.io/'
title: 'Varun Joshi'

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-cv

params:
  defer: false
