# The URL of your site.
baseURL: 'https://idjoshi.github.io/'

# The name of your site.
title: 'Varun Joshi'

# The theme to use.
theme:
  - github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

#############################
# The KEY Configuration Change
#############################
# This tells Hugo to treat the page for the author 'admin' as the homepage.
# This bypasses the entire 'blox' system that was causing all the errors.
cascade:
  - _target:
      kind: page
      path: /authors/admin/**
    params:
      layout: cv
      is_homepage: true
#############################

# Do not change the settings below.
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
enableRobotsTXT: true
