baseURL: 'https://idjoshi.github.io/'
title: 'Varun Joshi'

# This section correctly loads all necessary theme components.
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-cv

# Required parameter to prevent template error
defer: false
