imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
    disable: false
    ignoreConfig: false
    ignoreImports: false
    metadata:
      version: "v0.2.2"  # ✅ SAFE version for GitHub build server

mounts:
  - source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
    includeFiles: '**.html'
  - source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
    includeFiles: '**.html'
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    includeFiles: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
